### ISSUE TITLE
Problems with actual citizenship clause and my idea of citizenship as a privilege

### ISSUE THREAD

**Issue by ShikiGami** [liberland/constitution#522] opened 2016-09-01 11:28 UTC
For what I can understand from the current draft (2016/09/01) of the constitution, the citizenship is a double jus-sanguinis where only when 2 parents are citizens, the children automatically gets the citizenship.
The first problem, which I've seen has already been discussed here, but I would like to brought again with some extra points, if the fact of the "2 parents" requirement.
I fear that 2 parents could mean that, for example, a single mother who gives birth to a child, where the father is in the legal sense not available, would not be able to give the citizenship to the child, and therefore the child would be under international law "stateless".
There are many cases, where I can see a child becoming stateless, like the one of the parents is not a liberland citizen, but his country won't recognize the child as national (for example, in the future there is another country with a double jus-sanguinis clause like the one on the current draft of liberland).

Also I have a general problem with jus-sanguinis as the main method of obtaining citizenship.
This is a new country project, and as such this is actually a country that starts with a population of 0. Which means that all the people who will become citizens of this country will have to basically naturalize in order to get the citizenship. As far as I understand, right now the process of naturalization implies a review of your application for citizenship, to see if you are worth of the citizenship, and then you pay for it using the merits system.

Which makes me wonder, why would the children of a citizen should automatically get the citizenship if this is the case.
For all we know, these children could become hard communists, or bring some other ideology incompatible with the principles of liberland.
For them liberland citizenship wouldn't be something they fought in order to get, but something they just got for free, but if they were to apply as their parents for the citizenship, they would probably be rejected, but even so they could become active nativists who think they have the right to be against everything liberland stands for, just because they happened to be born to 2 liberland parents.

Which brings 2 interesting points. Citizenship in the sense of having the right to permanently reside in the country, and to be protected by the constitution, and Citizenship in the sense of international law.

International law basically asumes jus-sanguinis as a "must" for any country, so in order to comply with the law, you shouldn't let anyone to become stateless. But that is in the face of international law, but I would like to suggest a very different way to see citizenship.

The model I would like to propose is the "Citizenship as a privilege" model.
In this model, basically there would be no jus-sanguinis, and every single person should comply with the citizenship requirements in order to get it. Basically, making every single citizen a naturalized citizen.

And in order to solve the problems I said earlier, I would like to propose the "Citizenship candidate" or "pre-citizen" classification. This classification will be under international law the same as citizenship, but only when the "pre-citizen" doesn't have a second citizenship, basically, someone who is only a "pre-citizen" of liberland.

The status of pre-citizenship could be given under jus-sanguinis of citizens or other pre-citizens, and could also serve as a classification for immigrants who want to become citizens of liberland.

With a little more tweak of this idea, this could also apply as the classification of a citizens who have lost their privilege to hold office.
The idea is that in order to participate politically as a full member of society, people must prove themselves to abide to the ideals of the liberland constitution.

**Comment by liberlandcitizen** [comment] 2016-09-01 16:39
Shiki - get out of my brain! I have been having these same thoughts in
recent months and I have been meaning to bring up this subject here. I
agree 100% with everything you are saying. There has never been a country
before that started with zero people. Liberland can be thought of as a
place where every resident, visitor and citizen comes to it not from birth
but by free-will. Any offspring will be born because of the decisions of
their ancestors to go to Liberland. Future generations could have rights to
residency, but not automatic right to citizenship. I think everybody should
have completely equal rights and freedoms and even a passport (with two
types of passports issued) for those who would otherwise be stateless. It
just comes down to voting and running for office. They must be willing to
abide by the constitution and the philosophy of liberty or otherwise they
should not qualify to do either of those things.

This almost reminds me of a communist single-party system, and that might
scare those who believe in freedom. But when the party philosophy itself is
freedom, and is there to protect against people who may vote freedom away,
I personally feel ok with it. Maybe we need to think of our nation more as
an association, where we all must sign and agree to certain terms in order
to join it.

The question is, who will decide who gets citizenship with voting
privileges? It should probably fall to a large group of citizens (not
government). Hopefully ones that are neighbors, co-workers and friends with
the person. If enough people sign off on the person and if the person
swears to liberty, then they can be a full-on citizen.

**Comment by Auahi** [comment] 2016-09-02 02:48
I despise the notion of government being able to limit people's political rights based on their ideology. This isn't free speech. Also, I don't support the current government's agenda of blocking nazis, and communists from obtaining full citizenship. 

Now that being said, I'm much more comfortable if we had a system of naturalisation like that of Liechtenstein, where the community you live in can vote to accept or deny you citizenship. Or in Bermuda, where citizens can give testimonies during a citizenship hearing to either help support or oppose your citizenship decision.

A system not based on merits, but on community consensus makes more sense.

In this system we can have Provisional Citizenship, as mentioned by ShikiGami, and _Noble_ (Title TBD) Citizenship. A Provisional citizen has the right to domicile, a passport and follows jus sanguines, whereas a Noble Citizen has the added right to participate in government. 

This idea seems weird to me though, almost reminiscent of how africans couldn't vote in South Africa, or blacks in America.

**Comment by liberlandcitizen** [comment] 2016-09-02 05:19
It's nothing against holding communists or nazi beliefs per se, they are
free to believe as they wish. The problem for liberty comes when a majority
of people share any particular viewpoint. Once a majority of people hold
that viewpoint in a democracy, that viewpoint will be forced upon the
minority that do not. In most European countries these days, that viewpoint
is socialism. In Turkey we are seeing Islam overtaking the minority via
democracy (at least it was democratic for a long time).

Our constitution is strong but how can we preserve liberty for all future
generations? Certainly the first generation of citizens can be carefully
selected based on their viewpoints, but when they have kids who knows what
they will believe. And who knows who will make their way into our borders
and what philosophies they may bring with them.

We've fought for our country and we don't have anywhere else to be free.
How can we preserve it?

I love the idea of everybody having to naturalize, even offspring, based on
a clear criteria of what they must believe in: the non-aggression
principle, freedom of personal choice, respect for private property,
limited government, neutrality when it comes to foreign affairs and of
course a belief that taxation is theft. I agree that having the community
voting on each application could be a good thing. I do have a fear that the
community could be racist about it, but hopefully we are better than that.
Written testimonies don't mean much. I had to do those for my wife to gain
US citizenship and it was all too easy to get friends to write nice thing
(all true of course but still). But having to present yourself, answer
questions as to your beliefs, perhaps have people of the community
testifying for you followed by a vote of the community would be a good way
of doing this.

One thing I would suggest though is that all citizenship levels should be
able to veto bills since all people would have to live under all laws
passed and abide by all laws passed. And in fact all other rights of
citizenship should be granted to all.

But when it comes to the matter of voting people into office, and who gets
to serve in office, I feel like that should be from a pool of liberty
minded citizens only.

**Comment by liberlandcitizen** [comment] 2016-09-02 05:30
I recall seeing video of when the president handed out the first honorary
citizenships for Liberland. He said, "Do you swear for liberty?"

It was probably a joke, but I like it.

**Comment by Auahi** [comment] 2016-09-02 17:54
So the more and more we talk about this, the more it sounds like a communistic one party system, as mentioned previously. 

So essentially the only people that can partake in government are _Noble_ citizens (I don't know what term to use). Most likely all of these _noble_ citizens will be highly active in government, so to be a part of government (_Noble citizens_) you have to be accepted by the government first LOL.

**Comment by liberlandcitizen** [comment] 2016-09-02 18:06
​Very few people will be in the government because we'll have such a small,
limited government. It can't be said that we'll have "taxation without
representation" because there will be no taxes, just donations and
crowd-funded projects. Unless we do add in taxation (which I hope we
won't). And again I do think all residents should be able to take part in
the vetoing of laws.

My hope is that most people will understand the concept of Liberland,
embrace it and pledge to follow the constitution. That way most people can
gain true citizenship. Liberland is so small and there are so many other
places to go if they hold different beliefs. The question is, how many
people will take their pledge seriously once they have the citizenship?

**Comment by Auahi** [comment] 2016-09-02 18:10
Other full citizens can make a petition to strip one of their full-citizenship. If you're voted in and you change, you can be voted out.

**Comment by liberlandcitizen** [comment] 2016-09-02 18:35
I don't know, this is getting a little too hardcore even for me. It is like
communists where your party loyalty is being constantly tested. That's a
bit too much don't you think?

**Comment by ShikiGami** [comment] 2016-09-02 18:58
I think Auahi is going a little bit to far with this point, but I think there is something important in his statement.

In order to prevent a system where most of the people are not citizens, or prevent creating 2 different class of people, the law should be such that society should be encouraged to become citizens.
For this, the guidelines in order to get citizenship must be clear and trying to avoid ambiguities.
Also the guidelines for citizenship must be reasonable and just.

One of the things that occurred to me is that one of the main points of naturalization, as it happens in most countries in the world should be length of residence. Basically all "Citizenship candidates" could have their pre-citizenship almost automatically upgraded to citizenship when the minimal length of residence required is fulfilled.

The idea behind is that most people will become citizens, unless there is something that violates the requirements for citizenship.

Also, refusals could be appealed in court, and people should be encouraged to do so.

But the point is that citizenship shouldn't be a given for just having parents of the same citizenship, making everyone a naturalized citizen instead of a "blood" citizen; while also guarantying to that people who are not yet citizens, or for some reason cannot become citizens, that their rights are still protected under the constitution.

In the world right now most people become citizen either from blood or place of birth, and just a few undergo naturalization, which is a little bit ironic, because naturalized citizens, who have to actually prove themselves in order to get a citizenship usually are discriminated by "blood" citizens or even at times by the law.

One good example is how in many countries you cannot actually hold high level offices if you are not a "blood" citizen, if you are born outside of the country, or just if you have 2 or more citizenships.

The way I envisioned what I'm proposing is actually a way to fix all these problems.

**Comment by liberlandcitizen** [comment] 2016-09-02 19:48
I can't say that I agree that "length of residency" is the best merit to
judge citizenship worthiness on with regard to Liberland. I too hope that
most residents will be citizens, but only because they believe strongly in
Liberland, what it stands for, and want to defend liberty with their votes.

I hope Liberland will be flooded with people interested in liberty, but in
reality it could be flooded with people looking for prosperity, a new
passport, access to Europe or who knows what else. Liberty could mean
nothing to a bunch of people who come in to work construction. Should the
majority of that group be able to vote Liberland away from liberty and into
something else? We'll just end up like every other country.

At a very minimum it would be nice if we could explain what citizenship
means in Liberland and what ideals citizens are sworn to uphold. Whether
people will take those pledges seriously or not, who can say?

I know when you naturalize in the US, you must confirm multiple times that
you are not a communist. This is leftover from the cold-war and is probably
a bit outdated, but it exists. In Switzerland they can keep you from
becoming a citizen if you refuse to conform to the local culture. I've
heard of muslims not being granted citizenship because they don't let their
kids take swimming classes in public schools. In other words, we wouldn't
be the first nation to require philosophical conformity before granting
citizenship.

**Comment by Auahi** [comment] 2016-09-02 20:02
Disclaimer: I'm just throwing ideas out there, nothing I'm not saying is set in stone.

Should Liberland have jus sanguines, yes. It really will be a problem for children if it doesn't, now am I entirely comfortable with the two-tier citizenship no. I'd rather see a provisional citizenship given to minors, allocating them the same rights as residents with the added benefit of a passport. This makes the most sense in my eyes.

**Comment by Auahi** [comment] 2016-09-02 20:03
Disclaimer: I'm just throwing ideas out there, nothing I'm not saying is set in stone.

Should Liberland have jus sanguines, yes. It really will be a problem for children if it doesn't, now am I entirely comfortable with the two-tier citizenship, no. I'd rather see a provisional citizenship given to minors, allocating them the same rights as residents with the added benefit of a passport. This makes the most sense in my eyes.

**Comment by terrorist96** [comment] 2016-09-02 20:16
> Should the majority of that group be able to vote Liberland away from liberty and into
something else?

Isn't that the whole point of having a constitution? Where the majority can't vote away the liberties of the minority? If we were a direct democracy country without a constitution to safeguard your rights, then I'd be worried, But we're not.

**Comment by liberlandcitizen** [comment] 2016-09-02 20:22
<<isn't that the whole point of having a constitution? Where the majority
can't vote away the liberties of the minority?>>

I fear the constitution being ignored by voters, politicians and radical
judges. Do you agree this is a valid fear?

**Comment by terrorist96** [comment] 2016-09-03 04:22
> I fear the constitution being ignored by voters, politicians and radical
judges. Do you agree this is a valid fear?

Of course, which is why we try our best to make the consequences of violating the constitution as real as possible (see §III.3., §IX.7., recall referendums, etc.).

**Comment by liberlandcitizen** [comment] 2016-09-03 04:57
We've done a good job on the constitution, there are a lot of checks in
place and hopefully it will work forever. My fear is that if a population
isn't holding politicians feet to the fire at all times (seems to happen in
many countries even with relatively open democracy and many political
freedoms) the politicians will use and abuse their authority and ignore the
constitution. As a last line of defense, it may be good to have people who
are especially committed to the cause be the ones who are actually
recalling and voting the bums out, rather than the general population. But
I've made on my point on this enough, and I may be asking us to take it too
far - I don't know.

I will say again though that the idea of everybody having to naturalize
rather than being born with citizenship is brilliant and at the very least
I think we should have that. And having them pledge to uphold the values of
liberty seems reasonable as well. Ultimately no society can flourish with
freedom no matter what we do if that society is made up of people who don't
care about liberty.

**Comment by ConnectorLL** [comment] 2016-09-06 00:26
I think there should be Jus sanguinis in place to prevent statelessness. Constitution itself is well written to basicly lock everything in place. If it will be in future ignored. We don't know, but if there is need people will probably find a way to acheive it. If you left majority of people outside system and something went wrong way you risk revolution which will change all the roules. If people don't like the system they are living in they will change it one way or another. So the best way is to search for balance.

**Comment by michalptacnik** [comment] 2022-08-02 13:36
Closing the issue due to inactivity, we have a new draft of the constitution here: https://docs.google.com/document/d/1J2o5N9JDOzBXRkefe9Azm6P6vAwqCxw7B2jcKoHSjhg/edit

We do have ius sanguini now in our draft citizenship law, please track the corresponding issue in liberland/laws.

**Closed by michalptacnik** 2022-08-02 13:36 UTC
