### ISSUE TITLE
Transparency and efficiency 

### ISSUE THREAD

**Issue by saintego** [liberland/constitution#388] opened 2016-01-22 14:54 UTC
I didn't read constitution for a while so maybe now it's different, but I don't remember any section about having transparent government. It would be nice to force government to publish all data, except data that can endanger security and privacy of individuals. With this you can create pressure at government to be less corrupted and more efficient. 
You can create even more pressure by forcing government to reward anybody who will find inefficient law or any spending of government. I think it'll be enough to give right to anybody to ask for reward, let's say 10% of saved money(maybe for year), for finding more effective way of reaching goal of some law or cheaper way of some government spending. If he do not receive his reward he'll sue government on court or even better in front of International Chamber of Commerce or some other international arbiter, so government will not be able to influence judges.
Government will be able to defend itself just by telling it is needed because of international deals, constitution or something else that is meaningful.
With this you can catch some official buying some overpriced stuff, because he is corrupted or just don't care about public budget, by finding contract after publishing it, finding cheaper opinion and asking for reward. But what is more important if you find some regulation forcing average citizen let's say to spend 1 hour per year with some bureaucratic stuff and you'll be able to proof it is not necessary you can ask and sue government for (hourly wage \* population)/10. It can be same also with economical and personal freedom if somebody is able to quantify the lost. 
It can be useful while all taxes are not voluntary and we have land fee here. I think this can help to keep government small. It'll be hard to explain before elections why there are some inefficient regulations and spendings, while land fee is so high. It can motivate citizens and companies to fight for their freedom and to limit government. It can be also used as some kind of force to revoke law that became obsolete.

**Comment by terrorist96** [comment] 2016-01-22 15:14
See I.13 for the current transparency provision.

**Comment by saintego** [comment] 2016-01-23 00:32
Maybe I don't understand it properly, but it's not forcing government to publish spending for example.

**Comment by terrorist96** [comment] 2016-01-23 07:41
Spending is contained within the annual budget legislation, which consists of assembly work, which would have to be publicly available information.

**Comment by KacperZajc** [comment] 2016-01-26 12:55
this provision is as comprehensive as it can get

**Comment by saintego** [comment] 2016-01-26 13:06
I didn't read it properly, but it seems to me that this will contains all spendings. But what about efficiency? Why not to use rewards as some motivation for obsolete law hunters?

**Comment by qm3ster** [comment] 2016-01-27 20:39
@saintego can you give me some kind of scope on what data the government has, what needs to be published, and what needs to strictly remain unpublished?

(In my consideration, with a government so pervasive as currently being proposed, can there really be a limit to how transparent an Assembly member needs to be? Can we really afford to give the Assembly members and, in fact any government employee, any privacy at all?)

**Comment by saintego** [comment] 2016-01-29 10:51
I'm not sure that by Constitution nowadays there will be published bills for buying pen for 1btc(obvious ineffective, maybe corruption) or there will be published only one line of office expenses, where you can hide what ever you want. 
I think everything should be published except security things. I think you don't want to publish passwords, information about classified witnesses, personal data of citizens(don't know if it is allowed to collect such information now), maybe  also not all personal information about state employees. What about source code of custom software? I'm not sure what should stay classified, but I think it should be just minor part of information. 
I think that more important is what you allow to do with such information. I think that reward system can help to keep government smaller

**Comment by qm3ster** [comment] 2016-01-31 00:16
1. All government purchases have to be published of course, on a per item basis. The running totals of products of these purchases have to also be retained. 
  - Small things like pens, paperclips, etc, can be logged as retired, or recounted in storage, by the large crate with known contents, not individual pieces.
  - Expensive objects shall have one person responsible. For instance:
    - Every member of the government will be personally financially responsible for the work laptop/phone, if such are provided.
    - Randomly selected members will be responsible for shared things like the printer, kitchen equipment over the course of their public office.
    - Drivers will be responsible for vehicles, if any.
- All government site, database, server, mobile/desktop client and dApp code MUST be open-source and 'Reproducible Build'.
- Can you give a concrete example of a piece of information that could be collected by the government, [officially, morally, and legitimately], that must not be publically accessible? I honestly fail to see any such information to date. I am not guaranteeing it does not exist, but can someone prove that it does? For instance, most court proceedings are best published immediately. Classified witnesses, if they found useful and allowed for in the constitution, might be a case where the information can be published upon closure of investigation or possibly, in cases of dire necessity, shredded.
- Passports should contain:
  1. Unique ID
  - A 'private' portion:
    - Changeable password/passphrase
    - Tangible 2nd factor, eg code generator
  - Mandatory Published:
      - public key
      - All present and past votes, including votes ignored during citizenship
      - All present and past land ownership
      - All present and past government positions
  - Voluntarily Publishable (either present and public, or not present at all):
    - Whatever contact information the person chooses to publish:
      - Name? 
      - Surname?
      - username?
      - email?
    - Whatever biometric and medical information the person chooses to publish, to help identify them in case of accident and know what the best course of medical action is
    - Whatever links to other Passports they choose to list, such as partners and children

**Comment by saintego** [comment] 2016-02-01 10:35
For sure passwords and private keys cannot be published. I'm not sure either if there is something more than. I'm use to that information during investigation are not public, but I'm not sure if it's right. Same with classified witnesses.
Main point of my comment was not transparency, where I just didn't remember if and how it is mentioned in constitution, but efficiency. Nobody responded on that yet.

**Comment by qm3ster** [comment] 2016-02-01 11:14
I am not sure incentivising efficiency review and keeping in place an apparatus for processing improvement like that will be an overall benefit.
For instance, imagine someone notes that purchasing a different brand of pens that is are discontinued and at a discount would allow for more kilometers of ink per satoshi. Or that over the full estimated period of amortisation a more expensive government vehicle would have at the current fuel prices end up saving money over the whole purchase and operation cycle.
Both of these are factually true in the strictest sense, and so have no reason to be rejected in any court of reason. But neither of them is worth rewarding, as the findings would become obsolete by the next buying period, and the cost of proceedings outweighs the calculated savings.

**Comment by saintego** [comment] 2016-02-01 18:46
I don't think that the cost of proceedings outweighs the calculated
savings. It can be worthy to start the process only when reward is higher
that cost of someones time to find this inefficiency, someones time
to prepare for court, someones time in front of court and everything is
with some risk of loosing that case. If the discount had been not easy to
find you can also tell that extra payed money for normal pens would be
still better than paying somebody for searching for that discount.
Reward is just 10% from saved money. So even the findings can
became obsolete, it is obviously possible to save same amount of money by
doing better market research next time, for example by using know how that
was used as proof in front of court, or just offer that reward before next
buying period will happened.
Maybe you'll ask what with small spending. Probably someone will take it in
front of court only when he accumulate more similar issues.

**Comment by qm3ster** [comment] 2016-02-02 20:32
What about open tenders? Citizens can submit their offers of ten billion kilometers of pen and the lowest price is selected. Since the citizens will be able to leave some pie for themselves, they will be incentivised. But the government will still take the lowest non-idiotic offer.

**Comment by saintego** [comment] 2016-02-02 21:48
Yes but who decide that wait for open tender make sense and when it is
cheaper to buy pen in shop cross the street? What if condition of tender
will be stupid, like only pure gold pen, or something?

**Comment by qm3ster** [comment] 2016-02-03 14:39
If an idiotic bill, the execution of which requires pure gold pens, passes
its way to budgeting, we should at least ensure the pens are obtained in an
economical fashion and not from the legislator's cousin. I think this is a
valid line to separate the concerns at.

**Comment by saintego** [comment] 2016-02-04 07:55
Yes with open tender you can have cheapest golden pen, but with reward
system you can have just pen. Somebody can sue state for unnecessarity of
golden pen and with this build the pressure on that rule in reward system.
You have even much bigger chance that rule like that will not ever
happened, just because legislator will know what will happen next in reward
system.

**Closed** 2022-08-02 13:39 UTC
